### ISSUE TITLE
Some popular words not included

### ISSUE THREAD

**Issue by freealise** [hackerb9/gwordlist#1]
None of the shortened files contain, for example, the word "university".

**Comment by hackerb9** [comment]
Well.... that's mighty peculiar! The Google corpus is a bit lopsided, but that shouldn't happen. Perhaps it's an error in my script. What other words have gone missing?

**Comment by freealise** [comment]
abbey
academy
acronym
addictive
african
alaska
america
american
amendment

The plural 'universities' is there.
Maybe this is due to capitalization?

**Comment by hackerb9** [comment]
Sure enough, all of those words show up more frequently capitalized than not and my script tries to keep the capitalization (e.g., "London", not "london"). I think I forgot to use `grep -i`. Thanks for pointing this out, I'm fixing up my script now.

**Comment by hackerb9** [comment]
I think I've fixed the script and I've updated the [WordNet file](https://github.com/hackerb9/gwordlist/blob/master/frequency-alpha-wn.txt).  The other dictionaries I'll run later, after I update to the latest Google corpus.  

Let me know if this gives you the results you expect.

**Comment by freealise** [comment]
Yes, the rest of the words are not in the GCIDE, whose file I happened to be using.
Actually, before you fixed this, I managed to fetch the data with Google Scripts into a spreadsheet from [PhraseFinder](https://phrasefinder.io). 
I'm not sure if it's open source but maybe you might join effort.
